name: Build, Test & Publish

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    uses: pygmystack/.github/workflows/container-build-test-publish.yml@main
    with:
      image_name: ssh-agent
      replace_source: ghcr.io/pygmystack/ssh-agent:main
      oc_authors: the pygmy stack, Will Maier (original Docker image)
      oc_description: SSH agent service, configured for use with the pygmy stack
    secrets: inherit
